import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const sourceRoot = join(packageRoot, "src");
const outputRoot = join(packageRoot, "dist");
const checkOnly = process.argv.includes("--check");
const sourceFiles = ["primitives.json", "semantic.json", "components.json"];

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function merge(target, source) {
  for (const [key, value] of Object.entries(source)) {
    if (isObject(value) && isObject(target[key]) && !("$value" in value)) {
      merge(target[key], value);
    } else {
      target[key] = value;
    }
  }
  return target;
}

function collect(node, path = [], inheritedType, result = new Map()) {
  const groupType = node?.$type ?? inheritedType;
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const tokenPath = [...path, key];
    if (isObject(value) && "$value" in value) {
      result.set(tokenPath.join("."), {
        path: tokenPath,
        type: value.$type ?? groupType ?? "unknown",
        value: value.$value
      });
    } else if (isObject(value)) {
      collect(value, tokenPath, value.$type ?? groupType, result);
    }
  }
  return result;
}

const referencePattern = /^\{([^}]+)\}$/;
const cssName = (path) =>
  `--it-${path
    .split(".")
    .map((part) => part.replace(/_/g, "-"))
    .join("-")}`;

function resolveReference(value, tokens, stack = []) {
  if (typeof value !== "string") return value;
  const match = value.match(referencePattern);
  if (!match) return value;
  const path = match[1];
  if (!tokens.has(path)) {
    throw new Error(`Unknown token reference: ${value}`);
  }
  if (stack.includes(path)) {
    throw new Error(`Circular token reference: ${[...stack, path].join(" -> ")}`);
  }
  return resolveReference(tokens.get(path).value, tokens, [...stack, path]);
}

function cssValue(value, tokens) {
  if (typeof value !== "string") return String(value);
  const match = value.match(referencePattern);
  if (!match) return value;
  if (!tokens.has(match[1])) {
    throw new Error(`Unknown token reference: ${value}`);
  }
  return `var(${cssName(match[1])})`;
}

function setNested(target, path, value) {
  let cursor = target;
  for (const key of path.slice(0, -1)) {
    cursor[key] ??= {};
    cursor = cursor[key];
  }
  cursor[path.at(-1)] = value;
}

function formatTypeScript(value) {
  return `export const tokens = ${JSON.stringify(value, null, 2)} as const;

export type IntelluricTokens = typeof tokens;
export default tokens;
`;
}

function formatCss(tokens, themes) {
  const declarations = [...tokens.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([path, token]) => `  ${cssName(path)}: ${cssValue(token.value, tokens)};`);

  const themeBlocks = Object.entries(themes).map(([themeName, mappings]) => {
    const lines = Object.entries(mappings).map(
      ([path, value]) => `  ${cssName(path)}: ${cssValue(value, tokens)};`
    );
    return `[data-accent="${themeName}"] {\n${lines.join("\n")}\n}`;
  });

  return `/* Generated by packages/design-tokens/scripts/build.mjs. Do not edit. */
:root {
${declarations.join("\n")}
}

${themeBlocks.join("\n\n")}
`;
}

async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

async function compareOrWrite(path, content) {
  if (checkOnly) {
    let existing = "";
    try {
      existing = await readFile(path, "utf8");
    } catch {
      throw new Error(`Missing generated output: ${path}`);
    }
    if (existing !== content) {
      throw new Error(`Generated output is stale: ${path}`);
    }
    return;
  }
  await writeFile(path, content, "utf8");
}

const merged = {};
for (const file of sourceFiles) {
  merge(merged, await readJson(join(sourceRoot, file)));
}
const themes = await readJson(join(sourceRoot, "themes.json"));
const tokens = collect(merged);

for (const [path, token] of tokens) {
  resolveReference(token.value, tokens, [path]);
}
for (const mappings of Object.values(themes)) {
  for (const value of Object.values(mappings)) {
    resolveReference(value, tokens);
  }
}

const resolved = {};
for (const token of tokens.values()) {
  setNested(resolved, token.path, resolveReference(token.value, tokens));
}

const css = formatCss(tokens, themes);
const typescript = formatTypeScript(resolved);
const json = `${JSON.stringify(resolved, null, 2)}\n`;

await mkdir(outputRoot, { recursive: true });
await compareOrWrite(join(outputRoot, "tokens.css"), css);
await compareOrWrite(join(outputRoot, "tokens.ts"), typescript);
await compareOrWrite(join(outputRoot, "tokens.resolved.json"), json);

console.log(
  checkOnly
    ? `Token outputs are current (${tokens.size} tokens).`
    : `Generated ${tokens.size} tokens.`
);

